// apps/web/app/pages/gpu-specs/index.vue
<script setup lang="ts">
import { Search, Cpu, Gauge, MemoryStick, CalendarDays } from "lucide-vue-next";
import { Card, CardContent } from "~/components/ui/card";
import { Button } from "~/components/ui/button";

type GpuCatalogItem = {
	id: string;
	name: string;
	url: string;
	imageUrl: string | null;
	specs: Record<string, string>;
	updatedAt: string;
};

type GpuCatalogResponse = {
	items: GpuCatalogItem[];
	total: number;
};

useHead({
	title: "GPU Specs",
});

const search = ref("");

const query = computed(() => ({
	search: search.value || undefined,
	limit: 200,
}));

const { data, pending, refresh } = await useFetch<GpuCatalogResponse>("/api/gpu-specs", {
	query,
});

function spec(item: GpuCatalogItem, key: string): string {
	return item.specs[key] || "-";
}

function hasSpec(item: GpuCatalogItem, key: string): boolean {
	return Boolean(item.specs[key] && item.specs[key] !== "-");
}
</script>

<template>
	<div class="space-y-6">
		<div class="flex flex-wrap items-end justify-between gap-3">
			<div>
				<h1 class="text-2xl font-bold tracking-tight">GPU Specs</h1>
				<p class="text-sm text-muted-foreground">
					Catálogo visual das GPUs, focado nas especificações principais do chip.
				</p>
			</div>
			<Button variant="outline" @click="refresh()">Atualizar</Button>
		</div>

		<Card>
			<CardContent class="p-4">
				<label class="relative block">
					<Search class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
					<input
						v-model="search"
						type="text"
						placeholder="Buscar GPU (ex.: 4070, 7900, A770)"
						class="h-10 w-full rounded-md border bg-background pl-9 pr-3 text-sm"
					/>
				</label>
			</CardContent>
		</Card>

		<p class="text-sm text-muted-foreground">
			{{ pending ? "Carregando..." : `${data?.total ?? 0} GPUs encontradas` }}
		</p>

		<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
			<NuxtLink
				v-for="item in data?.items"
				:key="item.id"
				:to="`/gpu-specs/${item.id}`"
				class="group rounded-xl border bg-card p-3 transition hover:border-primary/40 hover:shadow-sm"
			>
				<div class="flex gap-3">
					<div class="size-24 shrink-0 overflow-hidden rounded-md border bg-muted/30">
						<img
							v-if="item.imageUrl"
							:src="item.imageUrl"
							:alt="item.name"
							class="size-full object-cover"
							loading="lazy"
						/>
						<div v-else class="flex size-full items-center justify-center">
							<Cpu class="size-6 text-muted-foreground" />
						</div>
					</div>
					<div class="min-w-0 flex-1">
						<p class="line-clamp-2 font-semibold leading-snug">{{ item.name }}</p>
						<p class="mt-1 text-xs text-muted-foreground">{{ spec(item, "architecture") }}</p>
					</div>
				</div>

				<div class="mt-3 grid grid-cols-2 gap-2 text-xs">
					<div v-if="hasSpec(item, 'boost_clock')" class="rounded-md border p-2">
						<p class="flex items-center gap-1 text-muted-foreground"><Gauge class="size-3.5" /> Boost</p>
						<p class="mt-0.5 font-medium">{{ spec(item, "boost_clock") }}</p>
					</div>
					<div v-if="hasSpec(item, 'memory_size')" class="rounded-md border p-2">
						<p class="flex items-center gap-1 text-muted-foreground">
							<MemoryStick class="size-3.5" /> Memoria
						</p>
						<p class="mt-0.5 font-medium">{{ spec(item, "memory_size") }}</p>
					</div>
					<div v-if="hasSpec(item, 'memory_bus')" class="rounded-md border p-2">
						<p class="flex items-center gap-1 text-muted-foreground"><Cpu class="size-3.5" /> Bus</p>
						<p class="mt-0.5 font-medium">{{ spec(item, "memory_bus") }}</p>
					</div>
					<div v-if="hasSpec(item, 'release_date')" class="rounded-md border p-2">
						<p class="flex items-center gap-1 text-muted-foreground">
							<CalendarDays class="size-3.5" /> Lancamento
						</p>
						<p class="mt-0.5 font-medium">{{ spec(item, "release_date") }}</p>
					</div>
				</div>
			</NuxtLink>
		</div>
	</div>
</template>

// apps/web/app/(routes)/gpu-specs/page.tsx
import { Search, Cpu, Gauge, MemoryStick, CalendarDays } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { redirect } from "next/navigation";

interface GpuCatalogItem {
	id: string;
	name: string;
	url: string;
	imageUrl: string | null;
	specs: Record<string, string>;
	updatedAt: string;
}

interface GpuCatalogResponse {
	items: GpuCatalogItem[];
	total: number;
}

async function getGpuSpecs(search?: string) {
	const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
	const url = new URL(`${baseUrl}/api/gpu-specs`);
	if (search) url.searchParams.set("search", search);
	url.searchParams.set("limit", "50");

	const res = await fetch(url.toString(), {
		cache: "no-store",
	});

	if (!res.ok) {
		return { items: [], total: 0 };
	}

	return await res.json();
}

function spec(item: GpuCatalogItem, key: string): string {
	return item.specs[key] || "-";
}

function hasSpec(item: GpuCatalogItem, key: string): boolean {
	return Boolean(item.specs[key] && item.specs[key] !== "-");
}

export default async function GpuSpecsPage({
	searchParams,
}: {
	searchParams: Promise<{ search?: string }>;
}) {
	const { search } = await searchParams;
	const data: GpuCatalogResponse = await getGpuSpecs(search);

	async function handleSearch(formData: FormData) {
		"use server";
		const searchForm = formData.get("search") as string;
		if (searchForm) {
			redirect(`/gpu-specs?search=${encodeURIComponent(searchForm)}`);
		} else {
			redirect("/gpu-specs");
		}
	}

	return (
		<div className="space-y-6">
			<div className="flex flex-wrap items-end justify-between gap-3">
				<div>
					<h1 className="text-2xl font-bold tracking-tight">GPU Specs</h1>
					<p className="text-sm text-muted-foreground">
						Catálogo visual das GPUs, focado nas especificações principais do chip.
					</p>
				</div>
				<form
					action={async () => {
						"use server";
						redirect("/gpu-specs");
					}}
				>
					<Button variant="outline" type="submit">
						Atualizar
					</Button>
				</form>
			</div>

			<Card>
				<CardContent className="p-4">
					<form action={handleSearch} className="relative block">
						<Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
						<input
							name="search"
							defaultValue={search}
							type="text"
							placeholder="Buscar GPU (ex.: 4070, 7900, A770)"
							className="h-10 w-full rounded-md border bg-background pl-9 pr-3 text-sm focus-visible:outline-hidden focus-visible:ring-1 focus-visible:ring-ring"
						/>
					</form>
				</CardContent>
			</Card>

			<p className="text-sm text-muted-foreground">{data.total} GPUs encontradas</p>

			<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
				{data.items.map((item) => (
					<Link
						key={item.id}
						href={`/gpu-specs/${item.id}`}
						className="group rounded-xl border bg-card p-3 transition hover:border-primary/40 hover:shadow-sm"
					>
						<div className="flex gap-3">
							<div className="size-24 shrink-0 overflow-hidden rounded-md border bg-muted/30">
								{item.imageUrl ? (
									<img
										src={item.imageUrl}
										alt={item.name}
										className="size-full object-cover"
										loading="lazy"
									/>
								) : (
									<div className="flex size-full items-center justify-center">
										<Cpu className="size-6 text-muted-foreground" />
									</div>
								)}
							</div>
							<div className="min-w-0 flex-1">
								<p className="line-clamp-2 font-semibold leading-snug">{item.name}</p>
								<p className="mt-1 text-xs text-muted-foreground">{spec(item, "architecture")}</p>
							</div>
						</div>

						<div className="mt-3 grid grid-cols-2 gap-2 text-xs">
							{hasSpec(item, "boost_clock") && (
								<div className="rounded-md border p-2">
									<p className="flex items-center gap-1 text-muted-foreground">
										<Gauge className="size-3.5" /> Boost
									</p>
									<p className="mt-0.5 font-medium">{spec(item, "boost_clock")}</p>
								</div>
							)}
							{hasSpec(item, "memory_size") && (
								<div className="rounded-md border p-2">
									<p className="flex items-center gap-1 text-muted-foreground">
										<MemoryStick className="size-3.5" /> Memoria
									</p>
									<p className="mt-0.5 font-medium">{spec(item, "memory_size")}</p>
								</div>
							)}
							{hasSpec(item, "memory_bus") && (
								<div className="rounded-md border p-2">
									<p className="flex items-center gap-1 text-muted-foreground">
										<Cpu className="size-3.5" /> Bus
									</p>
									<p className="mt-0.5 font-medium">{spec(item, "memory_bus")}</p>
								</div>
							)}
							{hasSpec(item, "release_date") && (
								<div className="rounded-md border p-2">
									<p className="flex items-center gap-1 text-muted-foreground">
										<CalendarDays className="size-3.5" /> Lancamento
									</p>
									<p className="mt-0.5 font-medium">{spec(item, "release_date")}</p>
								</div>
							)}
						</div>
					</Link>
				))}
			</div>
		</div>
	);
}
